version: "3"
services:
  app:
    image: ghcr.io/nickshanks347/monitarr:latest@sha256:ba45015c688fbc56a201c13d51bb07d76adb0d4f008ce4468042b76c6f14f6e8
    ports:
      - ${PORT:-3000}:3000
    environment:
      - SONARR_URL=$SONARRURL
      - SONARR_API_KEY=$SONARRAPI
      - RADARR_URL=$RADARRURL
      - RADARR_API_KEY=$RADARRAPI
      - BASE_PATH=${CFURLPATH:-}
    restart: unless-stopped
#    healthcheck:
#      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000$${CFURLPATH:-} || exit 1"]
#      interval: 30s
#      timeout: 20s
#      retries: 3
#      start_period: 30s
    labels:
      #- autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${PORT:-3000}
      - dfgeneric.0.access.policy=${CFPOLICY:-default_tld}
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 

